services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: mario
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./notes-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notesdb
      SPRING_DATASOURCE_USERNAME: mario
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./notes-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:

