apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: notes-app
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db-service:5432/notesdb
  CORS_ALLOWED_ORIGINS: http://notes.local
